name: skeely, MySQL Migration linter
description: Parse and validate MySQL Migration
author: DeBeAndo
inputs:
  path:
    description: "Path of the directory to start to find *.sql to lint."
    required: true
  files:
    description: "List of files to lint, separated by space."
    required: true
  ignore:
    description: "List of codes to ignore for all tables."
    required: true
  comment:
    description: "Send summary as comment into GitHub."
    required: true
  repository:
    description: "Repository path on github."
    required: true
  pullrequest:
    description: "Pull request number."
    required: true
  token:
    description: "Token to auth in github."
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
