name: Lint

on: [push]
jobs:
  test:
    name: Lint assets examples
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: |
        go mod tidy
        go mod download
        go build -o mylinter main.go

    - name: Lint
      run: ./mylinter --path=assets/examples
