name: Lint

on: [push]
jobs:
  test:
    name: Check code quality and run tests
    runs-on: ubuntu-latest
    if: ${{needs.changedfiles.outputs.ts}}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: |
        go mod tidy
        go mod download
        go build -o mylinter main.go

    - name: Lint
      run: |
        declare -a FILES=$(git diff --name-only main...test)
        for f in "${FILES[@]}"
        do
          echo "${f}"
        done
