name: Lint

on: [pull_request]
jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
      with:
        files: |
          **/*.sql
    - uses: debeando/skeely@main
      with:
        files: ${{ steps.changed-files.outputs.all_changed_files }}
        comment: true
        repository: ${{ github.repository }}
        pullrequest: ${{ github.event.pull_request.number }}
        token: ${{ github.token }}
