name: Lint

on: [push, pull_request]
jobs:
  test:
    name: Check code quality and run tests
    runs-on: ubuntu-latest
    if: ${{needs.changedfiles.outputs.ts}}
    steps:
    - uses: actions/checkout@v3

    - uses: lots0logs/gh-action-get-changed-files@2.1.4
      id: files
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: |
        go mod tidy
        go mod download
        go build -o mylinter main.go

    - name: Printing
      run: |
        echo "All:"
        echo "${{ steps.files.outputs.all }}"

    - name: Lint
      run: |
        declare -a FILES=$(${{ steps.files.outputs.all }})
        for f in "${FILES[@]}"
        do
          echo "${f}"
        done
